color: sky
description: null
fieldLayouts:
  af54ed68-81c5-4f18-8124-05937fafae18:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-22T10:18:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 81919059-e174-463b-a07d-5909f22771d4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1db2bb71-4b34-490b-a437-4485acd1896f
        userCondition: null
handle: compNavigationLabel
hasTitleField: true
icon: bars
name: 'Navigation / Label'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
