color: violet
description: null
fieldLayouts:
  118c73b5-c294-4baf-bda2-0f605cbd2ec6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-02T12:00:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c2078d68-c6cf-42ee-ad68-931b8a4b5cdb # Link - Native
            handle: button
            includeInCards: false
            instructions: null
            label: Button
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35eccd8c-7a80-4452-8dfb-029ade24766e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-02T12:07:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 177e5629-be0d-45a5-8751-ee4a081d01d0 # Switch - Off
            handle: large
            includeInCards: false
            instructions: null
            label: Large
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dba2ca7-6750-4abe-9d92-ec4e65d8329e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ecb80fa8-bff5-4a0b-b7b8-47a27a1596f8
        userCondition: null
handle: compButton
hasTitleField: false
icon: link
name: Button
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
