color: sky
description: null
fieldLayouts:
  844543ef-7355-4efc-b7e3-a997bd8cc66d:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:5e2baca9-5c68-4147-b9e7-0df1a3d033d9'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-12T10:08:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c2078d68-c6cf-42ee-ad68-931b8a4b5cdb # Link - Native
            handle: button
            includeInCards: true
            instructions: null
            label: Button
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e2baca9-5c68-4147-b9e7-0df1a3d033d9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-12T10:13:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0447cefb-59e4-4cb5-8d80-93043e135445
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a84139ba-a4d1-4cac-8268-00dd67e4678a
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 690d9211-f702-467d-8ca2-0d8edd7ce213
        userCondition: null
handle: compNavigation
hasTitleField: false
icon: bars
name: Navigation
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{button.label}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
