color: null
description: null
fieldLayouts:
  7c64c4af-b4a9-41f9-805d-073a82e4cdb6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T12:40:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3abcc3c5-d419-42f9-93c1-7dbbf11c29da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 999ea520-c214-4a7e-a1ed-76c20b394b56
        userCondition: null
handle: etCategorry
hasTitleField: true
icon: filter
name: Category
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
