altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  09ec29d1-9f63-4048-a205-1da6002aa316:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-14T11:54:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 77c0da91-68f0-4d81-a798-92e39ee6b8d8
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-11-14T11:54:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 879feacd-f920-4489-80ce-ccf6b15244e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-01T14:41:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c05cf09b-1380-4613-8fd9-1e1a72af0e79 # Text - Single
            handle: mediaCaption
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e30c17b9-ffa5-4343-99ee-0f780e5e0ed0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-01T14:41:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c05cf09b-1380-4613-8fd9-1e1a72af0e79 # Text - Single
            handle: mediaCopyright
            includeInCards: false
            instructions: null
            label: Copyright
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48d2238f-4200-4601-8702-9f2157892222
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d496da4b-1ba4-4d69-9089-f5f10eff2045
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: ''
