columnSuffix: null
handle: switchOff
instructions: null
name: 'Switch - Off'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
