defaultPlacement: end
enableVersioning: true
entryTypes:
  - e695ec0b-5690-4d85-a2bc-cab65554571d # Page / Blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6eab4b84-63fb-4382-bdd7-d2bee959aafb: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _entry
    uriFormat: 'blog/{slug}'
type: channel
