defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 07c61af5-375b-4586-bb91-7fed5cbf160d # Search
handle: search
maxAuthors: 1
name: Search
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6eab4b84-63fb-4382-bdd7-d2bee959aafb: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _entry/index.twig
    uriFormat: search
type: single
