# .ddev/docker-compose.vite.yaml
services:
  web:
    expose:
      - "3000" # Vite-Dev-Server-Port
    environment:
      # Mapping HTTP/HTTPS for Router
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILPIT_PORT}:8025,3001:3000
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILPIT_HTTPS_PORT}:8025,3000:3000
